### ISSUE TITLE
Add support for Azure Devops Integration properties to be compatible with version 1.18 of Backstage

### ISSUE THREAD

**Issue by germelindam** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#17]
When using the software template actions the _cloneAzureRepo_ (and I'm assuming the subsequent actions relating to Azure repo) fails with: "No token provided for Azure Integration". 
After checking this comes due to the new Backstage release version 1.18 and the deprecation of the token field for the Azure Devops Integration.  The new structure is as follows:

```
integrations:
  azure:
    - host: dev.azure.com
      credentials:
      - organizations:
         - organizationName
        personalAccessToken: ${PAT}
```

But the backend logic as shown [here](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories/blob/0.2.5-next.1/src/actions/run/cloneAzureRepo.ts#L87-L89) still refers to the old structure and this brings misleading errors when in fact the authorisation should work.
I believe updating the `integrationConfig` variable to mirror the new structure should fix it.
