### ISSUE TITLE
Azure Clone Repo unable to checkout to branch other than master

### ISSUE THREAD

**Issue by GDivino** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#33]
# Problem
While trying to clone a repo using the `azure:repo:clone` action, I noticed that I am not able to use the branch input successfully (unless we specify the default branch).

# Code
```
id: cloneRepo
name: Clone Azure Repo
action: azure:repo:clone
input:
  remoteUrl: ...
  branch: new-branch
  targetPath: ./new-folder
```

# Error message
```
2024-06-12T14:11:59.000Z info: Creating new remote...
2024-06-12T14:11:59.000Z info: Checking out branch...
2024-06-12T14:11:59.000Z NotFoundError: Could not find origin/new-branch
```

For some reason, only using master works. Is this perhaps because the code clones the repository with only the default branch?

Anyone experienced the same issue and have workarounds to this?
